nginx:
  image: nginx:latest
  ports:
    - "80:80"
  links:
    - "php-fpm"
  volumes:
    - ../srcList/docker/:/data/www
    - ./nginx/logs:/var/log/nginx
    - ./nginx/sites-enabled:/etc/nginx/conf.d

php-fpm:
  image: php:7.1-fpm
  ports:
    - "9000:9000"
  links:
    - "mysql"
  volumes:
    - ../srcList/docker/:/data/www

mysql:
  image: mysql:5.6
  ports:
    - "3306:3306"
  volumes:
    - ./mysql/data:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: root
