FROM mysql:5.7

ARG MYSQL_VERSION=5.7

MAINTAINER Bink Zhao <781270119@qq.com>

#####################################
# Set Timezone
#####################################

ARG TZ="Asia/Shanghai"
ENV TZ ${TZ}
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN chown -R mysql:root /var/lib/mysql/

ADD my.cnf /etc/mysql/conf.d/my.cnf

CMD ["mysqld"]

EXPOSE 3306
